services:
  watchalongago:
    build: .
    container_name: watchalongago
    env_file:
      - .env
    environment:
      - PUID=1000 # Update to match your local Arch user ID
      - PGID=1000 # Update to match your local Arch group ID
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ./static:/app/static
    ports:
      - "8080:8000"
    restart: unless-stopped