//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchBack.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontendStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontendStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WatchBack.Resources.FrontendStrings", typeof(FrontendStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        public static string Common_Saving {
            get {
                return ResourceManager.GetString("Common_Saving", resourceCulture);
            }
        }
        
        public static string Common_Saved {
            get {
                return ResourceManager.GetString("Common_Saved", resourceCulture);
            }
        }
        
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        public static string Common_Testing {
            get {
                return ResourceManager.GetString("Common_Testing", resourceCulture);
            }
        }
        
        public static string Common_Dismiss {
            get {
                return ResourceManager.GetString("Common_Dismiss", resourceCulture);
            }
        }
        
        public static string Common_Clearing {
            get {
                return ResourceManager.GetString("Common_Clearing", resourceCulture);
            }
        }
        
        public static string Common_Cleared {
            get {
                return ResourceManager.GetString("Common_Cleared", resourceCulture);
            }
        }
        
        public static string Common_Resetting {
            get {
                return ResourceManager.GetString("Common_Resetting", resourceCulture);
            }
        }
        
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        public static string Common_Copied {
            get {
                return ResourceManager.GetString("Common_Copied", resourceCulture);
            }
        }
        
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        public static string Auth_Username {
            get {
                return ResourceManager.GetString("Auth_Username", resourceCulture);
            }
        }
        
        public static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        public static string Auth_SigningIn {
            get {
                return ResourceManager.GetString("Auth_SigningIn", resourceCulture);
            }
        }
        
        public static string Auth_SignIn {
            get {
                return ResourceManager.GetString("Auth_SignIn", resourceCulture);
            }
        }
        
        public static string Auth_SignOut {
            get {
                return ResourceManager.GetString("Auth_SignOut", resourceCulture);
            }
        }
        
        public static string Auth_Theme {
            get {
                return ResourceManager.GetString("Auth_Theme", resourceCulture);
            }
        }
        
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        public static string Auth_InitialCredentials {
            get {
                return ResourceManager.GetString("Auth_InitialCredentials", resourceCulture);
            }
        }
        
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        public static string Auth_ConnectionFailed {
            get {
                return ResourceManager.GetString("Auth_ConnectionFailed", resourceCulture);
            }
        }
        
        public static string Auth_SetupFailed {
            get {
                return ResourceManager.GetString("Auth_SetupFailed", resourceCulture);
            }
        }
        
        public static string Auth_PasswordRequired {
            get {
                return ResourceManager.GetString("Auth_PasswordRequired", resourceCulture);
            }
        }
        
        public static string Auth_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Auth_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        public static string Auth_PasswordChangeFailed {
            get {
                return ResourceManager.GetString("Auth_PasswordChangeFailed", resourceCulture);
            }
        }
        
        public static string Setup_Title {
            get {
                return ResourceManager.GetString("Setup_Title", resourceCulture);
            }
        }
        
        public static string Setup_Subtitle {
            get {
                return ResourceManager.GetString("Setup_Subtitle", resourceCulture);
            }
        }
        
        public static string Setup_NewUsername {
            get {
                return ResourceManager.GetString("Setup_NewUsername", resourceCulture);
            }
        }
        
        public static string Setup_ChooseUsername {
            get {
                return ResourceManager.GetString("Setup_ChooseUsername", resourceCulture);
            }
        }
        
        public static string Setup_NewPassword {
            get {
                return ResourceManager.GetString("Setup_NewPassword", resourceCulture);
            }
        }
        
        public static string Setup_ChoosePassword {
            get {
                return ResourceManager.GetString("Setup_ChoosePassword", resourceCulture);
            }
        }
        
        public static string Setup_PasswordWeak {
            get {
                return ResourceManager.GetString("Setup_PasswordWeak", resourceCulture);
            }
        }
        
        public static string Setup_PasswordFair {
            get {
                return ResourceManager.GetString("Setup_PasswordFair", resourceCulture);
            }
        }
        
        public static string Setup_PasswordStrong {
            get {
                return ResourceManager.GetString("Setup_PasswordStrong", resourceCulture);
            }
        }
        
        public static string Setup_PasswordVeryWeak {
            get {
                return ResourceManager.GetString("Setup_PasswordVeryWeak", resourceCulture);
            }
        }
        
        public static string Setup_PasswordVeryStrong {
            get {
                return ResourceManager.GetString("Setup_PasswordVeryStrong", resourceCulture);
            }
        }
        
        public static string Setup_Complete {
            get {
                return ResourceManager.GetString("Setup_Complete", resourceCulture);
            }
        }
        
        public static string PasswordUpdate_Title {
            get {
                return ResourceManager.GetString("PasswordUpdate_Title", resourceCulture);
            }
        }
        
        public static string PasswordUpdate_Message {
            get {
                return ResourceManager.GetString("PasswordUpdate_Message", resourceCulture);
            }
        }
        
        public static string PasswordUpdate_ConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordUpdate_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string PasswordUpdate_ReEnter {
            get {
                return ResourceManager.GetString("PasswordUpdate_ReEnter", resourceCulture);
            }
        }
        
        public static string PasswordUpdate_Update {
            get {
                return ResourceManager.GetString("PasswordUpdate_Update", resourceCulture);
            }
        }
        
        public static string Nav_Configuration {
            get {
                return ResourceManager.GetString("Nav_Configuration", resourceCulture);
            }
        }
        
        public static string Nav_Sync {
            get {
                return ResourceManager.GetString("Nav_Sync", resourceCulture);
            }
        }
        
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        public static string Nav_Diagnostics {
            get {
                return ResourceManager.GetString("Nav_Diagnostics", resourceCulture);
            }
        }
        
        public static string Config_Integrations {
            get {
                return ResourceManager.GetString("Config_Integrations", resourceCulture);
            }
        }
        
        public static string Config_TestConnection {
            get {
                return ResourceManager.GetString("Config_TestConnection", resourceCulture);
            }
        }
        
        public static string Config_TestAll {
            get {
                return ResourceManager.GetString("Config_TestAll", resourceCulture);
            }
        }
        
        public static string Config_AllConnected {
            get {
                return ResourceManager.GetString("Config_AllConnected", resourceCulture);
            }
        }
        
        public static string Config_AllFailed {
            get {
                return ResourceManager.GetString("Config_AllFailed", resourceCulture);
            }
        }
        
        public static string Config_SomeFailed {
            get {
                return ResourceManager.GetString("Config_SomeFailed", resourceCulture);
            }
        }
        
        public static string Config_Set {
            get {
                return ResourceManager.GetString("Config_Set", resourceCulture);
            }
        }
        
        public static string Config_Unchanged {
            get {
                return ResourceManager.GetString("Config_Unchanged", resourceCulture);
            }
        }
        
        public static string Config_ClearOverride {
            get {
                return ResourceManager.GetString("Config_ClearOverride", resourceCulture);
            }
        }
        
        public static string Config_ResetTo {
            get {
                return ResourceManager.GetString("Config_ResetTo", resourceCulture);
            }
        }
        
        public static string Config_WatchData {
            get {
                return ResourceManager.GetString("Config_WatchData", resourceCulture);
            }
        }
        
        public static string Config_Posts {
            get {
                return ResourceManager.GetString("Config_Posts", resourceCulture);
            }
        }
        
        public static string Config_From {
            get {
                return ResourceManager.GetString("Config_From", resourceCulture);
            }
        }
        
        public static string Config_NotConfigured {
            get {
                return ResourceManager.GetString("Config_NotConfigured", resourceCulture);
            }
        }
        
        public static string Config_CommentsFrom {
            get {
                return ResourceManager.GetString("Config_CommentsFrom", resourceCulture);
            }
        }
        
        public static string Config_Configured {
            get {
                return ResourceManager.GetString("Config_Configured", resourceCulture);
            }
        }
        
        public static string Config_NotConfiguredStatus {
            get {
                return ResourceManager.GetString("Config_NotConfiguredStatus", resourceCulture);
            }
        }
        
        public static string Config_Connected {
            get {
                return ResourceManager.GetString("Config_Connected", resourceCulture);
            }
        }
        
        public static string Config_ConnectionFailed {
            get {
                return ResourceManager.GetString("Config_ConnectionFailed", resourceCulture);
            }
        }
        
        public static string Config_RequestFailed {
            get {
                return ResourceManager.GetString("Config_RequestFailed", resourceCulture);
            }
        }
        
        public static string Preferences_Title {
            get {
                return ResourceManager.GetString("Preferences_Title", resourceCulture);
            }
        }
        
        public static string Preferences_WatchProvider {
            get {
                return ResourceManager.GetString("Preferences_WatchProvider", resourceCulture);
            }
        }
        
        public static string Preferences_TimeMachineWindow {
            get {
                return ResourceManager.GetString("Preferences_TimeMachineWindow", resourceCulture);
            }
        }
        
        public static string Preferences_RedditSearchEngine {
            get {
                return ResourceManager.GetString("Preferences_RedditSearchEngine", resourceCulture);
            }
        }
        
        public static string Preferences_CustomOption {
            get {
                return ResourceManager.GetString("Preferences_CustomOption", resourceCulture);
            }
        }
        
        public static string Preferences_CustomSearchUrlHelp {
            get {
                return ResourceManager.GetString("Preferences_CustomSearchUrlHelp", resourceCulture);
            }
        }
        
        public static string Preferences_SegmentedProgressBar {
            get {
                return ResourceManager.GetString("Preferences_SegmentedProgressBar", resourceCulture);
            }
        }
        
        public static string Preferences_AlwaysShowSearch {
            get {
                return ResourceManager.GetString("Preferences_AlwaysShowSearch", resourceCulture);
            }
        }
        
        public static string Preferences_SavePreferences {
            get {
                return ResourceManager.GetString("Preferences_SavePreferences", resourceCulture);
            }
        }
        
        public static string Preferences_Language {
            get {
                return ResourceManager.GetString("Preferences_Language", resourceCulture);
            }
        }
        
        public static string Locale_NativeName {
            get {
                return ResourceManager.GetString("Locale_NativeName", resourceCulture);
            }
        }
        
        public static string DangerZone_Title {
            get {
                return ResourceManager.GetString("DangerZone_Title", resourceCulture);
            }
        }
        
        public static string DangerZone_ResetPassword {
            get {
                return ResourceManager.GetString("DangerZone_ResetPassword", resourceCulture);
            }
        }
        
        public static string DangerZone_ResetPasswordTitle {
            get {
                return ResourceManager.GetString("DangerZone_ResetPasswordTitle", resourceCulture);
            }
        }
        
        public static string DangerZone_ResetPasswordHelp {
            get {
                return ResourceManager.GetString("DangerZone_ResetPasswordHelp", resourceCulture);
            }
        }
        
        public static string DangerZone_ResetPasswordDone {
            get {
                return ResourceManager.GetString("DangerZone_ResetPasswordDone", resourceCulture);
            }
        }
        
        public static string DangerZone_ClearCache {
            get {
                return ResourceManager.GetString("DangerZone_ClearCache", resourceCulture);
            }
        }
        
        public static string DangerZone_ClearCacheTitle {
            get {
                return ResourceManager.GetString("DangerZone_ClearCacheTitle", resourceCulture);
            }
        }
        
        public static string DangerZone_ClearCacheHelp {
            get {
                return ResourceManager.GetString("DangerZone_ClearCacheHelp", resourceCulture);
            }
        }
        
        public static string DangerZone_Restart {
            get {
                return ResourceManager.GetString("DangerZone_Restart", resourceCulture);
            }
        }
        
        public static string DangerZone_RestartHelp {
            get {
                return ResourceManager.GetString("DangerZone_RestartHelp", resourceCulture);
            }
        }
        
        public static string DangerZone_ForwardAuth {
            get {
                return ResourceManager.GetString("DangerZone_ForwardAuth", resourceCulture);
            }
        }
        
        public static string DangerZone_ForwardAuthHelp {
            get {
                return ResourceManager.GetString("DangerZone_ForwardAuthHelp", resourceCulture);
            }
        }
        
        public static string DangerZone_EnableForwardAuth {
            get {
                return ResourceManager.GetString("DangerZone_EnableForwardAuth", resourceCulture);
            }
        }
        
        public static string DangerZone_HeaderName {
            get {
                return ResourceManager.GetString("DangerZone_HeaderName", resourceCulture);
            }
        }
        
        public static string DangerZone_ForwardAuthWarning {
            get {
                return ResourceManager.GetString("DangerZone_ForwardAuthWarning", resourceCulture);
            }
        }
        
        public static string Time_SecondsAgo {
            get {
                return ResourceManager.GetString("Time_SecondsAgo", resourceCulture);
            }
        }
        
        public static string Time_MinutesAgo {
            get {
                return ResourceManager.GetString("Time_MinutesAgo", resourceCulture);
            }
        }
        
        public static string Time_HoursAgo {
            get {
                return ResourceManager.GetString("Time_HoursAgo", resourceCulture);
            }
        }
        
        public static string Diagnostics_ApplicationLogs {
            get {
                return ResourceManager.GetString("Diagnostics_ApplicationLogs", resourceCulture);
            }
        }
        
        public static string Diagnostics_LastSync {
            get {
                return ResourceManager.GetString("Diagnostics_LastSync", resourceCulture);
            }
        }
        
        public static string Diagnostics_NoSyncData {
            get {
                return ResourceManager.GetString("Diagnostics_NoSyncData", resourceCulture);
            }
        }
        
        public static string Diagnostics_Version {
            get {
                return ResourceManager.GetString("Diagnostics_Version", resourceCulture);
            }
        }
        
        public static string Diagnostics_All {
            get {
                return ResourceManager.GetString("Diagnostics_All", resourceCulture);
            }
        }
        
        public static string Diagnostics_DebugPlus {
            get {
                return ResourceManager.GetString("Diagnostics_DebugPlus", resourceCulture);
            }
        }
        
        public static string Diagnostics_InfoPlus {
            get {
                return ResourceManager.GetString("Diagnostics_InfoPlus", resourceCulture);
            }
        }
        
        public static string Diagnostics_WarningPlus {
            get {
                return ResourceManager.GetString("Diagnostics_WarningPlus", resourceCulture);
            }
        }
        
        public static string Diagnostics_ErrorPlus {
            get {
                return ResourceManager.GetString("Diagnostics_ErrorPlus", resourceCulture);
            }
        }
        
        public static string Diagnostics_NoLogs {
            get {
                return ResourceManager.GetString("Diagnostics_NoLogs", resourceCulture);
            }
        }
        
        public static string Diagnostics_Found {
            get {
                return ResourceManager.GetString("Diagnostics_Found", resourceCulture);
            }
        }
        
        public static string Diagnostics_NoEntriesMatchingFilter {
            get {
                return ResourceManager.GetString("Diagnostics_NoEntriesMatchingFilter", resourceCulture);
            }
        }
        
        public static string Diagnostics_DiagnosticLog {
            get {
                return ResourceManager.GetString("Diagnostics_DiagnosticLog", resourceCulture);
            }
        }
        
        public static string Diagnostics_Captured {
            get {
                return ResourceManager.GetString("Diagnostics_Captured", resourceCulture);
            }
        }
        
        public static string Diagnostics_Browser {
            get {
                return ResourceManager.GetString("Diagnostics_Browser", resourceCulture);
            }
        }
        
        public static string Diagnostics_Filter {
            get {
                return ResourceManager.GetString("Diagnostics_Filter", resourceCulture);
            }
        }
        
        public static string Diagnostics_Sync {
            get {
                return ResourceManager.GetString("Diagnostics_Sync", resourceCulture);
            }
        }
        
        public static string Diagnostics_Providers {
            get {
                return ResourceManager.GetString("Diagnostics_Providers", resourceCulture);
            }
        }
        
        public static string Diagnostics_Entries {
            get {
                return ResourceManager.GetString("Diagnostics_Entries", resourceCulture);
            }
        }
        
        public static string Dashboard_MediaSearch {
            get {
                return ResourceManager.GetString("Dashboard_MediaSearch", resourceCulture);
            }
        }
        
        public static string Dashboard_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Dashboard_SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string Dashboard_SearchMoviesTVShows {
            get {
                return ResourceManager.GetString("Dashboard_SearchMoviesTVShows", resourceCulture);
            }
        }
        
        public static string Dashboard_Searching {
            get {
                return ResourceManager.GetString("Dashboard_Searching", resourceCulture);
            }
        }
        
        public static string Dashboard_Search {
            get {
                return ResourceManager.GetString("Dashboard_Search", resourceCulture);
            }
        }
        
        public static string Dashboard_ManualOverride {
            get {
                return ResourceManager.GetString("Dashboard_ManualOverride", resourceCulture);
            }
        }
        
        public static string Dashboard_ClearManualState {
            get {
                return ResourceManager.GetString("Dashboard_ClearManualState", resourceCulture);
            }
        }
        
        public static string Dashboard_ProviderPlaying {
            get {
                return ResourceManager.GetString("Dashboard_ProviderPlaying", resourceCulture);
            }
        }
        
        public static string Dashboard_BrowseSeasons {
            get {
                return ResourceManager.GetString("Dashboard_BrowseSeasons", resourceCulture);
            }
        }
        
        public static string Dashboard_Back {
            get {
                return ResourceManager.GetString("Dashboard_Back", resourceCulture);
            }
        }
        
        public static string Dashboard_SelectSeason {
            get {
                return ResourceManager.GetString("Dashboard_SelectSeason", resourceCulture);
            }
        }
        
        public static string Dashboard_LoadingSeasons {
            get {
                return ResourceManager.GetString("Dashboard_LoadingSeasons", resourceCulture);
            }
        }
        
        public static string Dashboard_Season {
            get {
                return ResourceManager.GetString("Dashboard_Season", resourceCulture);
            }
        }
        
        public static string Dashboard_SeasonTitle {
            get {
                return ResourceManager.GetString("Dashboard_SeasonTitle", resourceCulture);
            }
        }
        
        public static string Dashboard_SeasonsBack {
            get {
                return ResourceManager.GetString("Dashboard_SeasonsBack", resourceCulture);
            }
        }
        
        public static string Dashboard_LoadingEpisodes {
            get {
                return ResourceManager.GetString("Dashboard_LoadingEpisodes", resourceCulture);
            }
        }
        
        public static string Dashboard_Aired {
            get {
                return ResourceManager.GetString("Dashboard_Aired", resourceCulture);
            }
        }
        
        public static string Dashboard_Syncing {
            get {
                return ResourceManager.GetString("Dashboard_Syncing", resourceCulture);
            }
        }
        
        public static string Dashboard_NothingPlaying {
            get {
                return ResourceManager.GetString("Dashboard_NothingPlaying", resourceCulture);
            }
        }
        
        public static string Dashboard_NothingPlayingDetail {
            get {
                return ResourceManager.GetString("Dashboard_NothingPlayingDetail", resourceCulture);
            }
        }
        
        public static string Dashboard_ErrorOccurred {
            get {
                return ResourceManager.GetString("Dashboard_ErrorOccurred", resourceCulture);
            }
        }
        
        public static string Dashboard_ErrorDetail {
            get {
                return ResourceManager.GetString("Dashboard_ErrorDetail", resourceCulture);
            }
        }
        
        public static string Dashboard_NoDiscussions {
            get {
                return ResourceManager.GetString("Dashboard_NoDiscussions", resourceCulture);
            }
        }
        
        public static string Dashboard_NoDiscussionsDetail {
            get {
                return ResourceManager.GetString("Dashboard_NoDiscussionsDetail", resourceCulture);
            }
        }
        
        public static string Dashboard_TimeMachine {
            get {
                return ResourceManager.GetString("Dashboard_TimeMachine", resourceCulture);
            }
        }
        
        public static string Dashboard_AllComments {
            get {
                return ResourceManager.GetString("Dashboard_AllComments", resourceCulture);
            }
        }
        
        public static string Dashboard_NoCommentsMatchFilter {
            get {
                return ResourceManager.GetString("Dashboard_NoCommentsMatchFilter", resourceCulture);
            }
        }
        
        public static string Dashboard_GroupByThread {
            get {
                return ResourceManager.GetString("Dashboard_GroupByThread", resourceCulture);
            }
        }
        
        public static string Dashboard_GroupedByThread {
            get {
                return ResourceManager.GetString("Dashboard_GroupedByThread", resourceCulture);
            }
        }
        
        public static string Dashboard_OmdbNotConfigured {
            get {
                return ResourceManager.GetString("Dashboard_OmdbNotConfigured", resourceCulture);
            }
        }
        
        public static string Dashboard_SearchFailed {
            get {
                return ResourceManager.GetString("Dashboard_SearchFailed", resourceCulture);
            }
        }
        
        public static string Dashboard_ConnectionFailed {
            get {
                return ResourceManager.GetString("Dashboard_ConnectionFailed", resourceCulture);
            }
        }
        
        public static string Dashboard_LoadSeasonsFailed {
            get {
                return ResourceManager.GetString("Dashboard_LoadSeasonsFailed", resourceCulture);
            }
        }
        
        public static string Dashboard_LoadEpisodesFailed {
            get {
                return ResourceManager.GetString("Dashboard_LoadEpisodesFailed", resourceCulture);
            }
        }
        
        public static string Dashboard_SetWatchStateFailed {
            get {
                return ResourceManager.GetString("Dashboard_SetWatchStateFailed", resourceCulture);
            }
        }
        
        public static string Dashboard_ClearWatchStateFailed {
            get {
                return ResourceManager.GetString("Dashboard_ClearWatchStateFailed", resourceCulture);
            }
        }
        
        public static string Comments_By {
            get {
                return ResourceManager.GetString("Comments_By", resourceCulture);
            }
        }
        
        public static string Comments_Score {
            get {
                return ResourceManager.GetString("Comments_Score", resourceCulture);
            }
        }
        
        public static string Comments_ViewOn {
            get {
                return ResourceManager.GetString("Comments_ViewOn", resourceCulture);
            }
        }
        
        public static string Comments_MoreReplyInThread {
            get {
                return ResourceManager.GetString("Comments_MoreReplyInThread", resourceCulture);
            }
        }
        
        public static string Comments_MoreRepliesInThread {
            get {
                return ResourceManager.GetString("Comments_MoreRepliesInThread", resourceCulture);
            }
        }
        
        public static string Comments_ImageFromPost {
            get {
                return ResourceManager.GetString("Comments_ImageFromPost", resourceCulture);
            }
        }
        
        public static string Comments_ClickToEnlarge {
            get {
                return ResourceManager.GetString("Comments_ClickToEnlarge", resourceCulture);
            }
        }
        
        public static string Aria_SyncProgress {
            get {
                return ResourceManager.GetString("Aria_SyncProgress", resourceCulture);
            }
        }
        
        public static string Aria_CloseConfigPanel {
            get {
                return ResourceManager.GetString("Aria_CloseConfigPanel", resourceCulture);
            }
        }
        
        public static string Aria_MinimumLogLevel {
            get {
                return ResourceManager.GetString("Aria_MinimumLogLevel", resourceCulture);
            }
        }
        
        public static string Aria_ImageViewer {
            get {
                return ResourceManager.GetString("Aria_ImageViewer", resourceCulture);
            }
        }
        
        public static string Aria_EnlargedImage {
            get {
                return ResourceManager.GetString("Aria_EnlargedImage", resourceCulture);
            }
        }
        
        public static string Aria_ShowValue {
            get {
                return ResourceManager.GetString("Aria_ShowValue", resourceCulture);
            }
        }
        
        public static string Aria_HideValue {
            get {
                return ResourceManager.GetString("Aria_HideValue", resourceCulture);
            }
        }
        
        public static string Aria_Comments {
            get {
                return ResourceManager.GetString("Aria_Comments", resourceCulture);
            }
        }
        
        public static string Aria_ConfigSections {
            get {
                return ResourceManager.GetString("Aria_ConfigSections", resourceCulture);
            }
        }
    }
}
